config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'home#index' #home/index made root page 

  get 'home/about'

  get 'home/contact'
  
  get 'home/assess'
  
  get 'home/learn'
  
  get 'home/diary'

  get 'home/plans' => 'plans#index'
  
  get 'home/help'
  
  
  
  
  
  resources :plans
  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
    belongs_to :user
    belongs_to :plan
    has_many :plans
    has_many :items
    has_one :catalogue
end

app/models/plan.rb
class Plan < ActiveRecord::Base
    belongs_to :user
    has_many :items
    has_many :plans
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :plans
         has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/catalogue_controller.rb
class CatalogueController < ApplicationController
    def show
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
  
  def assess 
  end
  
  def learn
  end
  
  def diary
  end
  
  def help
  end
  
  def plans
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  #before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.order("category DESC").all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new 
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # Items category 
  #def category
   # @items = item.find_all_by_category(params[:id])
  #  @category = params[:id]
    
  #  respond_to do |format|
  #    format.html # index.html.erb
  #    format.json {render json: @items }
  #  end
 # end
      
  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  #def correct_user
   #@item = current_user.items.find_by(id: params[:id])   # current_user is a devise helper 
   #redirect_to items_path, notice: "Not allowed to edit items" if @item.nil?
  #end  
  
  def catalogue
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :category)
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  
  # need to authenticate the user before the CRUD is available to them 
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.order("created_at DESC").all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = current_user.plans.build
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = current_user.plans.build(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # define correct_user method and authorisation message 
  def correct_user
    @plan = current_user.plans.find_by(id: params[:id])   # current_user is a devise helper 
    redirect_to plans_path, notice: "You cannot view this plan - please login" if @plan.nil?
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:name, :planspace)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogue_helper.rb
module CatalogueHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/catalogue/catalogue.html.erb
<div id="container">

    <div id="plan-sidebar">              
            <button class="plans button-open">
            My Plans
            </button>

            <%#= link_to 'Edit', edit_item_path(item) %>
            <h2>Self-Care</h2>
              <h3>Select and add to your plan</h3>
              <ul id="carecategories">
                <li><%# link_to 'Show', items_catalogue_path %><b>Body<b></li>
                <li><%#= link_to=' '><b>Mind<b> %></li>
                <li><%#= link_to=' '><b>Spirit<b> %></li>
                <li><%#= link_to=' '><b>Workplace<b> %></li>
              </ul>         
    </div> 

    <div id="planspace"> 
           <!-- Care Items Catalogue-->
            <button class="planspace-buttons-new">
            New Plan
            </button>
          
            <button class="planspace-buttons-savespace">
            Save
            </button>
            
            <br><br>
            <br><br>

    <div id="itemswrap">
        <div id="itemscat">
            <table style="width:90%">
                <tr>
                    <td class="items"><%#= link_to 'Show', items_catalogue_path %><% image_tag src="images/body-icon.png" alt="Body" %></td>
                    <td class="items"><%#= link_to %><img src="images/mind-icon.png" alt="Mind"></td>
                </tr>                

                <tr>
                    <td class="desc"><%#= link_to="images/body-icon.png">Body< %></td>
                    <td class="desc"><%#= link_to="#">Mind%>></td>
                </tr>

                <tr>
                    <td class="items"><%#= link_to="/items/catalogue"><img src="images/spirit-icon.png" alt="Spirit"> %></td>
                    <td class="items"><%#= link_to="/items/catalogue"><img src="images/workplace-icon.png" alt="Workplace"> %></td>
                </tr>

                <tr>
                    <td class="desc"><%#= link_to="items/catalogue">Spirit< %></td>                    
                    <td class="desc"><%#= link_to="items/catalogue">Workplace< %></td>
                </tr>
            </table>
        </div> <!--end of itemscat-->    
    </div> <!-- end of itemswrap box -->

          <!--
          <div id="planspace-body">
          <h1>body</h1>
          </div>    

          <div id="planspace-mind">
          <h1>mind</h1>
          </div> 
          
          <div id="planspace-spirit">
          <h1>spirit</h1>
          </div>

          <div id="planspace-workplace">
          <h1>workplace</h1>
          </div>
          -->

    <div id="supportppl">
          <br>
          <textarea rows="5" cols="94" placeholder="comments"></textarea>
        
          <form action="#"> 
                My Support People: <br>
                <input type="textarea" name="mysupport"><br>
                Three Goals: <br>
                <input type="textarea" name="mygoals1" placeholder="name a goal"><br>
                <input type="textarea" name="mygoals2" placeholder="name a goal"><br>
                <input type="textarea" name="mygoals3" placeholder="name a goal"><br>
          </form>
 
          <button class="plans button-save">
           <b>Save Plan<b>
           </button>

          <button class="plans button-print">
            Print Plan
          </button>
    </div> <!-- end of supportppl div -->
  </div> <!-- end of container -->
  
<script type="text/javascript">
</script>

</body>

app/views/elements/_form.html.erb
<%= form_for(@element) do |f| %>
  <% if @element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
      <% @element.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :button_url %><br>
    <%= f.text_field :button_url %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home/_dash.html.erb
<%#= link_to 'Assess', home_assess_path %>
<%#= link_to 'Learn', home_learn_path %>
<%#= link_to 'Diary', home_diary_path %>

app/views/home/_header.html.erb
<nav class="navbar navbar-default" role="navigation">    <%# bootstrap nav component code #%> 
  <div class="container-fluid">
    <div class="navbar-header">
      <%= image_tag ("ISTIGH-Logo.png") %>
      <%= link_to 'Home', root_path %>
      <%= link_to 'About Us', home_about_path %>
      <%= link_to 'Contact', home_contact_path %>
      <%= link_to 'Help', home_help_path %>
    </div> 
    
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          
          <% if user_signed_in? %>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li><%= link_to "Join", new_user_registration_path %></li>
          <% end %> 
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Istigh</h1>
<p>Istigh is a self care planning tool, developed in response to the needs of employees, volunteers and clients in the Community and Voluntary Sector</p>

app/views/home/assess.html.erb
<h1> Assess </h1>

app/views/home/contact.html.erb
<h1>Contact Us</h1>
<p>If you are having any trouble using Istigh, please feel free to contact us.</p>

app/views/home/diary.html.erb
<h1>Self Care Diary</h1>
<h2>Keep track of your feelings and thoughts <br>
<p>Scaffold diary for CRUD functions with title, diary-entry. <br>
ID, timestamp as default as well as created_at and updated_at.</p>
</h2>

app/views/home/help.html.erb
<div>
    <h1>Need Help? Call xxxx</h1>
</div>

app/views/home/index.html.erb
<%# dashboard view %> 

<div class ="jumbotron">
    <h1>Welcome to Istigh</h1>
    <h2>Self Care Planning</h2>
    <p>Going inwards so you can keep moving onwards</p>
    <%= link_to 'Assess', home_assess_path, class: 'btn btn-default' %>   <%# bootstrap buttons %>
    <%= link_to 'Learn', home_learn_path, class: 'btn btn-default' %>     <%# bootstrap buttons %>
    <%= link_to 'Diary', home_diary_path, class: 'btn btn-default' %>     <%# bootstrap buttons %>
    <%= link_to 'Plan', home_plans_path, class: 'btn btn-default' %>      <%# bootstrap buttons %>
</div>

app/views/home/learn.html.erb
<div>
    <h1>Learn About Self Care</h1>
</div>

app/views/home/plans.html.erb
<% render 'plans/index' %>
<%# render 'items/catalogue'%>

app/views/items/_catalogue.html.erb
<title>Istigh | Plan </title>

  <div id="container">

    <div id="plan-sidebar">              
            <button class="plans button-open">
            My Plans
            </button>

            <%#= link_to 'Edit', edit_item_path(item) %>
            <h2>Self-Care</h2>
              <h3>Select and add to your plan</h3>
              <ul id="carecategories">
                <li><%# link_to 'Show', items_catalogue_path %><b>Body<b></li>
                <li><%#= link_to=' '><b>Mind<b> %></li>
                <li><%#= link_to=' '><b>Spirit<b> %></li>
                <li><%#= link_to=' '><b>Workplace<b> %></li>
              </ul>         
    </div> 

    <div id="planspace"> 
           <!-- Care Items Catalogue-->
            <button class="planspace-buttons-new">
            New Plan
            </button>
          
            <button class="planspace-buttons-savespace">
            Save
            </button>
            
            <br><br>
            <br><br>

    <div id="itemswrap">
        <div id="itemscat">
            <table style="width:90%">
                <tr>
                    <td class="items"><%#= link_to 'Show', items_catalogue_path %><image_tag="images/body-icon.png" alt="Body"%></td>
                    <td class="items"><%#= link_to %><img src="images/mind-icon.png" alt="Mind"></td>
                </tr>                

                <tr>
                    <td class="desc"><%#= link_to="images/body-icon.png">Body< %></td>
                    <td class="desc"><%#= link_to="#">Mind%>></td>
                </tr>

                <tr>
                    <td class="items"><%#= link_to="/items/catalogue"><img src="images/spirit-icon.png" alt="Spirit"> %></td>
                    <td class="items"><%#= link_to="/items/catalogue"><img src="images/workplace-icon.png" alt="Workplace"> %></td>
                </tr>

                <tr>
                    <td class="desc"><%#= link_to="items/catalogue">Spirit< %></td>                    
                    <td class="desc"><%#= link_to="items/catalogue">Workplace< %></td>
                </tr>
            </table>
        </div> <!--end of itemscat-->    
    </div> <!-- end of itemswrap box -->

          <!--
          <div id="planspace-body">
          <h1>body</h1>
          </div>    

          <div id="planspace-mind">
          <h1>mind</h1>
          </div> 
          
          <div id="planspace-spirit">
          <h1>spirit</h1>
          </div>

          <div id="planspace-workplace">
          <h1>workplace</h1>
          </div>
          -->

    <div id="supportppl">
          <br>
          <textarea rows="5" cols="94" placeholder="comments"></textarea>
        
          <form action="#"> 
                My Support People: <br>
                <input type="textarea" name="mysupport"><br>
                Three Goals: <br>
                <input type="textarea" name="mygoals1" placeholder="name a goal"><br>
                <input type="textarea" name="mygoals2" placeholder="name a goal"><br>
                <input type="textarea" name="mygoals3" placeholder="name a goal"><br>
          </form>
 
          <button class="plans button-save">
           <b>Save Plan<b>
           </button>

          <button class="plans button-print">
            Print Plan
          </button>
    </div> <!-- end of supportppl div -->
  </div> <!-- end of container -->
  
<script type="text/javascript">
</script>

</body>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path, class: 'btn btn-default' %>

app/views/items/index.html.erb
<%# <div id='category'>
  <% render '/items/categoryDistinctList' %> 

<%# render 'items/catalogue' %>

<p id="notice"><%= notice %></p>

<h1>Self Care Catalogue</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Category</th>
      <!-- <th>Image</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td class="items"><%= item.title %></td>
        <td><%= item.description %></td>
        <td class="items"><%= item.category %></td>
        <td><%= image_tag ("body-icon.png") %></td>
        <td><%#= item.image %></td>        
        
        <td><%= link_to 'Show', item, class: 'btn btn-default' %></td>
        
        <%# if @item.user == current_user %>
        <td><%= link_to 'Edit', edit_item_path(item), class: 'btn btn-default' %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %></td>
      </tr>

      <%# end %>
    <% end %>
  </tbody>
</table>      

<%= link_to 'New Item', new_item_path, class: 'btn btn-default' %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path, class: 'btn btn-default' %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Image:</strong>
  <%= @item.image %>
</p>

<%# if @item.user == current_user %>
<%= link_to 'Edit', edit_item_path(@item), class: 'btn btn-default' %> |
<%# end %>
<%= link_to 'Back', items_path, class: 'btn btn-default' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width", initial-scale="1", maximum-scale="1">
</head>

<body>
<%= render 'home/header' %>

<div class="container">
  <% flash.each do |name, msg| %>   <%# devise alerts %> 
  <% content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>
  
  <%#= render 'home/dash' %>
  
  <%= yield %>
  
</div>


</body>
</html>

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :planspace %><br>
    <%= f.text_field :planspace %>
  </div>
  
  <div class="actions">

    <b><%= f.submit %><b>

  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :planspace %><br>
    <%= f.text_field :planspace %>
  </div>
  
  <div class="actions">
    <b><%= f.submit %><b>

  </div>
<% end %>


<%= link_to 'Show', @plan, class: 'btn btn-default' %> |
<%= link_to 'Back', plans_path, class: 'btn btn-default' %>

app/views/plans/index.html.erb
<title>Istigh | Plan </title>

<p id="notice"><%= notice %></p>

<h1>My Plans</h1>

<%= link_to 'New Plan', new_plan_path, class: 'btn btn-default' %>      <%# bootstrap buttons %>
<br><br>
<%= link_to 'Self Care Pieces', items_path, class: 'btn btn-default' %>      <%# bootstrap buttons %>
 
<br><br>

<table id= "myplans">
<table>
  <thead>
    <tr>
      <th>Plan Name</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>        
      <% if plan.user == current_user %>
        <td><%= plan.name %></td>

        <td><%= link_to 'Show', plan, class: 'btn btn-default' %></td>  <%# bootstrap buttons %>
        <td><%= link_to 'Edit', edit_plan_path(plan), class: 'btn btn-default' %></td>  <%# bootstrap buttons %>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

 <div id="plan-sidebar">              
      <%#= link_to 'Edit', edit_item_path(item) %>
      <h2>Self Care</h2>
        <h3>Select and add to your plan</h3>
          <ul id="carecategories">
              <li><% link_to 'Items', items_path %><b>Items<b></li>
              <li><%#= link_to=' '><b>Mind<b> %></li>
              <li><%#= link_to=' '><b>Spirit<b> %></li>
              <li><%#= link_to=' '><b>Workplace<b> %></li>
          </ul>         
  </div> 

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path, class: 'btn btn-default' %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plan.name %>
</p>

<div id= "planspace">
  <strong>Plan Space:</strong>
  <br><br>
  <%= @plan.planspace %>
</div>

<div id="supportppl">
          <br>
          <textarea rows="5" cols="94" placeholder="comments"></textarea>
        
          <form action="#"> 
                My Support People: <br>
                <input type="textarea" name="mysupport"><br>
                Three Goals: <br>
                <input type="textarea" name="mygoals1" placeholder="name a goal"><br>
                <input type="textarea" name="mygoals2" placeholder="name a goal"><br>
                <input type="textarea" name="mygoals3" placeholder="name a goal"><br>
          </form>
          
           <button class="plans button-save">
            Save Plan
          </button>
          
          <button class="plans button-print">
            Print Plan
          </button>
</div> <!-- end of supportppl div -->


<% if @plan.user == current_user %>
<%= link_to 'Edit', edit_plan_path(@plan), class: 'btn btn-default' %> |
<% end %>

<%= link_to 'Back', plans_path, class: 'btn btn-default' %>